package com.krtc.practice.vo;

public class HAD02VO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB.TBHAD02.LOCNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    private String locNo;

    /**
     * 位置代碼
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB.TBHAD02.LOCDESC
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    private String locDesc;

    /**
     * 位置描述
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB.TBHAD02.STATUS
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    private String status;

    /**
     * 狀態
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB.TBHAD02.CRTEMPNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    private String crtEmpNo;

    /**
     * 新增人員
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB.TBHAD02.CRTDATE
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    private String crtDate;

    /**
     * 新增日期
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB.TBHAD02.UPTEMPNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    private String uptEmpNo;

    /**
     * 新增人員
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DB.TBHAD02.UPTDATE
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    private String uptDate;

    /**
     * 新增日期
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB.TBHAD02.LOCNO
     *
     * @return the value of DB.TBHAD02.LOCNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public String getLocNo() {
        return locNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB.TBHAD02.LOCNO
     *
     * @param locNo the value for DB.TBHAD02.LOCNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public void setLocNo(String locNo) {
        this.locNo = locNo == null ? null : locNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB.TBHAD02.LOCDESC
     *
     * @return the value of DB.TBHAD02.LOCDESC
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public String getLocDesc() {
        return locDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB.TBHAD02.LOCDESC
     *
     * @param locDesc the value for DB.TBHAD02.LOCDESC
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public void setLocDesc(String locDesc) {
        this.locDesc = locDesc == null ? null : locDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB.TBHAD02.STATUS
     *
     * @return the value of DB.TBHAD02.STATUS
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB.TBHAD02.STATUS
     *
     * @param status the value for DB.TBHAD02.STATUS
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB.TBHAD02.CRTEMPNO
     *
     * @return the value of DB.TBHAD02.CRTEMPNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public String getCrtEmpNo() {
        return crtEmpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB.TBHAD02.CRTEMPNO
     *
     * @param crtEmpNo the value for DB.TBHAD02.CRTEMPNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public void setCrtEmpNo(String crtEmpNo) {
        this.crtEmpNo = crtEmpNo == null ? null : crtEmpNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB.TBHAD02.CRTDATE
     *
     * @return the value of DB.TBHAD02.CRTDATE
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public String getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB.TBHAD02.CRTDATE
     *
     * @param crtDate the value for DB.TBHAD02.CRTDATE
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public void setCrtDate(String crtDate) {
        this.crtDate = crtDate == null ? null : crtDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB.TBHAD02.UPTEMPNO
     *
     * @return the value of DB.TBHAD02.UPTEMPNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public String getUptEmpNo() {
        return uptEmpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB.TBHAD02.UPTEMPNO
     *
     * @param uptEmpNo the value for DB.TBHAD02.UPTEMPNO
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public void setUptEmpNo(String uptEmpNo) {
        this.uptEmpNo = uptEmpNo == null ? null : uptEmpNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DB.TBHAD02.UPTDATE
     *
     * @return the value of DB.TBHAD02.UPTDATE
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public String getUptDate() {
        return uptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DB.TBHAD02.UPTDATE
     *
     * @param uptDate the value for DB.TBHAD02.UPTDATE
     *
     * @mbg.generated Tue Jul 18 10:17:44 CST 2023
     */
    public void setUptDate(String uptDate) {
        this.uptDate = uptDate == null ? null : uptDate.trim();
    }
}